version: '3.9'

services:
  mongo_db:
    container_name: mongo_db_container
    image: mongo:4.1.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  api:
    container_name: node_container
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
